#!/usr/bin/env node
/**
 * Compare two real-device series generated by device-monitor.js.
 * This is a conditional P1 review aid, not a certificate that the game is fun.
 * Exit 0 PASS, 2 REVIEW/FAIL, 3 NOT_COMPARABLE, 1 usage/read failure.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const args={maxRegression:10,require30fps:false};
for(let i=2;i<process.argv.length;i++){
  const arg=process.argv[i];
  if(arg==="--require-30fps"){args.require30fps=true;continue;}
  if(!["--baseline","--candidate","--out","--max-p95-regression"].includes(arg)||!process.argv[i+1]){
    console.error("Usage: node compare-device.mjs --baseline before.json --candidate after.json [--out review.json] [--max-p95-regression 10] [--require-30fps]");
    process.exit(1);
  }
  const key=arg.slice(2);args[key]=process.argv[++i];
}
if(!args.baseline||!args.candidate) throw new Error("Provide --baseline and --candidate from device-monitor.js downloadAll()");
args.maxRegression=Number(args["max-p95-regression"]??args.maxRegression);
if(!Number.isFinite(args.maxRegression)||args.maxRegression<0||args.maxRegression>100)throw new Error("--max-p95-regression must be 0–100");
const before=JSON.parse(readFileSync(resolve(args.baseline),"utf8"));
const after=JSON.parse(readFileSync(resolve(args.candidate),"utf8"));
const base=before.runs||[],current=after.runs||[],notes=[];
if(before.measurementClass!=="real browser/device page-side timing; not GPU utilization"||after.measurementClass!==before.measurementClass)
  notes.push("Both files must be raw real-device series exported by device-monitor.js");
if(base.length<3||current.length<3||base.length!==current.length)notes.push("Both files need equal counts of at least 3 runs; reload page between scenarios");
const identity=r=>{
  const m=r.metadata||{},s=m.screen||{};
  return [m.label,m.scenario,m.seed,m.userAgent,m.platform,m.renderer,m.graphicsLevel,m.graphicsName,
    m.renderDist,s.innerWidth,s.innerHeight,s.dpr,s.width,s.height].map(x=>String(x??"missing")).join("|");
};
const runs=[...base,...current];
if(!runs.length||!runs.every(r=>identity(r)===identity(runs[0])))notes.push("Environment mismatch: label/scenario/seed/browser/renderer/graphics/render distance/viewport/DPR must match");
if(runs.some(r=>!r.metadata?.revision||r.metadata.revision==="not-recorded"))notes.push("Record a real revision/commit for each run");
if(runs.some(r=>!r.metadata?.seed||r.metadata.seed==="unknown"))notes.push("Seed metadata missing");
if(base.some(r=>r.metadata?.revision!==base[0]?.metadata?.revision)||current.some(r=>r.metadata?.revision!==current[0]?.metadata?.revision))notes.push("Each series must have one consistent revision");
if(base[0]?.metadata?.revision===current[0]?.metadata?.revision)notes.push("Baseline and candidate revisions are the same; no before/after conclusion");
if(runs.some(r=>r.stopReason!=="duration"||r.requestedSeconds<30||r.actualSeconds<29||r.rafFrames<30||r.hiddenDuringRun!==false||
  !Array.isArray(r.runtimeErrors)||r.runtimeErrors.length||!Number.isFinite(r.p95FrameMs)||r.p95FrameMs<=0||
  !Number.isFinite(r.longestSlowStreakMs)||!Number.isFinite(r.particlePeak)||typeof r.particleCapExceeded!=="boolean"))
  notes.push("Invalid run: require >=30s, >=30 RAF samples, visible page, no runtime errors, finite p95/streak/particle metrics");
const changed=runs.filter(r=>r.graphicsNameEnd!==r.metadata?.graphicsName||r.renderDistEnd!==r.metadata?.renderDist);
if(changed.length)notes.push(`${changed.length} run(s) auto-adjusted graphics or render distance; p95 is not a fixed-load comparison`);
const median=xs=>{const s=[...xs].sort((a,b)=>a-b);return (s[Math.floor((s.length-1)/2)]+s[Math.floor(s.length/2)])/2;};
const baseP95=base.length?median(base.map(r=>r.p95FrameMs)):null;
const currentP95=current.length?median(current.map(r=>r.p95FrameMs)):null;
const regressionPct=baseP95>0&&Number.isFinite(currentP95)?+((currentP95-baseP95)/baseP95*100).toFixed(2):null;
const particleViolations=current.filter(r=>r.particleCapExceeded===true).length;
const slowRuns=current.filter(r=>r.longestSlowStreakMs>=5000).length;
let gate;
if(notes.length||regressionPct===null)gate="NOT_COMPARABLE";
else if(particleViolations)gate="REVIEW_PARTICLE_CAP";
else if(args.require30fps&&slowRuns)gate="REVIEW_SUSTAINED_SLOW_FRAMES";
else if(regressionPct>args.maxRegression)gate="REVIEW_P95_REGRESSION";
else gate="PASS_PROVISIONAL_REAL_DEVICE";
const result={schemaVersion:1,gate,baselineRevision:base[0]?.metadata?.revision??null,candidateRevision:current[0]?.metadata?.revision??null,
  baselineFile:resolve(args.baseline),candidateFile:resolve(args.candidate),runCount:[base.length,current.length],
  environment:current[0]?.metadata??null,medianP95Ms:{baseline:baseP95,candidate:currentP95},regressionPct,
  thresholdPercent:args.maxRegression,require30fps:args.require30fps,slowRuns,particleViolations,
  notes:[...notes,"PASS is provisional: human telegraph/touch feel and independent GPU/thermal checks remain necessary"]};
if(args.out)writeFileSync(resolve(args.out),JSON.stringify(result,null,2)+"\n");
console.log(JSON.stringify(result,null,2));
process.exitCode=gate==="PASS_PROVISIONAL_REAL_DEVICE"?0:gate==="NOT_COMPARABLE"?3:2;
